const types = {
    FETCH_FINANCE_KPI_START: 'FETCH_FINANCE_KPI_START',
    FETCH_FINANCE_KPI_SUCCESS: 'FETCH_FINANCE_KPI_SUCCESS',
    FETCH_FINANCE_KPI_FAILURE: 'FETCH_FINANCE_KPI_FAILURE',
}

export default types;