const productionDetailsTypes = {

    FETCH_PRODUCTION_DETAILS_START: 'FETCH_PRODUCTION_DETAILS_START',
    FETCH_PRODUCTION_DETAILS_SUCCESS: 'FETCH_PRODUCTION_DETAILS_SUCCESS',
    FETCH_PRODUCTION_DETAILS_FAILURE: 'FETCH_PRODUCTION_DETAILS_FAILURE',

    FETCH_DAILY_SCRAP_BY_CODE_START: 'FETCH_DAILY_SCRAP_BY_CODE_START',
    FETCH_DAILY_SCRAP_BY_CODE_SUCCESS: 'FETCH_DAILY_SCRAP_BY_CODE_SUCCESS',
    FETCH_DAILY_SCRAP_BY_CODE_FAILURE: 'FETCH_DAILY_SCRAP_BY_CODE_FAILURE',
}

export default productionDetailsTypes;