const MorningMeetingTypes = {
    FETCH_SAFETY_MONTHLY_INCIDENT_RATE_START: 'FETCH_SAFETY_MONTHLY_INCIDENT_RATE_START',
    FETCH_SAFETY_MONTHLY_INCIDENT_RATE_SUCCESS: 'FETCH_SAFETY_MONTHLY_INCIDENT_RATE_SUCCESS',
    FETCH_SAFETY_MONTHLY_INCIDENT_RATE_FAILURE: 'FETCH_SAFETY_MONTHLY_INCIDENT_RATE_FAILURE',

    FETCH_SAFETY_INCIDENTS_BY_DEPT_START: 'FETCH_SAFETY_INCIDENTS_BY_DEPT_START',
    FETCH_SAFETY_INCIDENTS_BY_DEPT_SUCCESS: 'FETCH_SAFETY_INCIDENTS_BY_DEPT_SUCCESS',
    FETCH_SAFETY_INCIDENTS_BY_DEPT_FAILURE: 'FETCH_SAFETY_INCIDENTS_BY_DEPT_FAILURE',

    FETCH_SAFETY_INCIDENTS_START: 'FETCH_SAFETY_INCIDENTS_START',
    FETCH_SAFETY_INCIDENTS_SUCCESS: 'FETCH_SAFETY_INCIDENTS_SUCCESS',
    FETCH_SAFETY_INCIDENTS_FAILURE: 'FETCH_SAFETY_INCIDENTS_FAILURE',

    FETCH_LOGISTICS_STOCK_OVERVIEW_START: 'FETCH_LOGISTICS_STOCK_OVERVIEW_START',
    FETCH_LOGISTICS_STOCK_OVERVIEW_SUCCESS: 'FETCH_LOGISTICS_STOCK_OVERVIEW_SUCCESS',
    FETCH_LOGISTICS_STOCK_OVERVIEW_FAILURE: 'FETCH_LOGISTICS_STOCK_OVERVIEW_FAILURE'
}

export default MorningMeetingTypes;