const MorningMeetingTypes = {
    FETCH_SAFETY_MONTHLY_INCIDENT_RATE_START: 'FETCH_SAFETY_MONTHLY_INCIDENT_RATE_START',
    FETCH_SAFETY_MONTHLY_INCIDENT_RATE_SUCCESS: 'FETCH_SAFETY_MONTHLY_INCIDENT_RATE_SUCCESS',
    FETCH_SAFETY_MONTHLY_INCIDENT_RATE_FAILURE: 'FETCH_SAFETY_MONTHLY_INCIDENT_RATE_FAILURE'
}

export default MorningMeetingTypes;