const MorningMeetingTypes = {
    FETCH_SAFETY_MONTHLY_INCIDENT_RATE_START: 'FETCH_SAFETY_MONTHLY_INCIDENT_RATE_START',
    FETCH_SAFETY_MONTHLY_INCIDENT_RATE_SUCCESS: 'FETCH_SAFETY_MONTHLY_INCIDENT_RATE_SUCCESS',
    FETCH_SAFETY_MONTHLY_INCIDENT_RATE_FAILURE: 'FETCH_SAFETY_MONTHLY_INCIDENT_RATE_FAILURE',

    FETCH_SAFETY_INCIDENTS_BY_DEPT_START: 'FETCH_SAFETY_INCIDENTS_BY_DEPT_START',
    FETCH_SAFETY_INCIDENTS_BY_DEPT_SUCCESS: 'FETCH_SAFETY_INCIDENTS_BY_DEPT_SUCCESS',
    FETCH_SAFETY_INCIDENTS_BY_DEPT_FAILURE: 'FETCH_SAFETY_INCIDENTS_BY_DEPT_FAILURE',

    FETCH_SAFETY_INCIDENTS_START: 'FETCH_SAFETY_INCIDENTS_START',
    FETCH_SAFETY_INCIDENTS_SUCCESS: 'FETCH_SAFETY_INCIDENTS_SUCCESS',
    FETCH_SAFETY_INCIDENTS_FAILURE: 'FETCH_SAFETY_INCIDENTS_FAILURE',

    FETCH_LOGISTICS_STOCK_OVERVIEW_START: 'FETCH_LOGISTICS_STOCK_OVERVIEW_START',
    FETCH_LOGISTICS_STOCK_OVERVIEW_SUCCESS: 'FETCH_LOGISTICS_STOCK_OVERVIEW_SUCCESS',
    FETCH_LOGISTICS_STOCK_OVERVIEW_FAILURE: 'FETCH_LOGISTICS_STOCK_OVERVIEW_FAILURE',

    FETCH_LOGISTICS_STOCK_OVERVIEW_SLOC_START: 'FETCH_LOGISTICS_STOCK_OVERVIEW_SLOC_START',
    FETCH_LOGISTICS_STOCK_OVERVIEW_SLOC_SUCCESS: 'FETCH_LOGISTICS_STOCK_OVERVIEW_SLOC_SUCCESS',
    FETCH_LOGISTICS_STOCK_OVERVIEW_SLOC_FAILURE: 'FETCH_LOGISTICS_STOCK_OVERVIEW_SLOC_FAILURE',

    FETCH_LOGISTICS_STATUS_START: 'FETCH_LOGISTICS_STATUS_START',
    FETCH_LOGISTICS_STATUS_SUCCESS: 'FETCH_LOGISTICS_STATUS_SUCCESS',
    FETCH_LOGISTICS_STATUS_FAILURE: 'FETCH_LOGISTICS_STATUS_FAILURE',

    FETCH_PRODUCTION_STATUS_START: 'FETCH_PRODUCTION_STATUS_START',
    FETCH_PRODUCTION_STATUS_SUCCESS: 'FETCH_PRODUCTION_STATUS_SUCCESS',
    FETCH_PRODUCTION_STATUS_FAILURE: 'FETCH_PRODUCTION_STATUS_FAILURE',

    FETCH_DAILY_SCRAP_RATE_START: 'FETCH_DAILY_SCRAP_RATE_START',
    FETCH_DAILY_SCRAP_RATE_SUCCESS: 'FETCH_DAILY_SCRAP_RATE_SUCCESS',
    FETCH_DAILY_SCRAP_RATE_FAILURE: 'FETCH_DAILY_SCRAP_RATE_FAILURE',

    FETCH_DAILY_KPI_START: 'FETCH_DAILY_KPI_START',
    FETCH_DAILY_KPI_SUCCESS: 'FETCH_DAILY_KPI_SUCCESS',
    FETCH_DAILY_KPI_FAILURE: 'FETCH_DAILY_KPI_FAILURE',

    FETCH_WEEKLY_LABOR_HRS_START: 'FETCH_WEEKLY_LABOR_HRS_START',
    FETCH_WEEKLY_LABOR_HRS_SUCCESS: 'FETCH_WEEKLY_LABOR_HRS_SUCCESS',
    FETCH_WEEKLY_LABOR_HRS_FAILURE: 'FETCH_WEEKLY_LABOR_HRS_FAILURE',

    FETCH_PROD_SCRAP_START: 'FETCH_PROD_SCRAP_START',
    FETCH_PROD_SCRAP_SUCCESS: 'FETCH_PROD_SCRAP_SUCCESS',
    FETCH_PROD_SCRAP_FAILURE: 'FETCH_PROD_SCRAP_FAILURE'
}

export default MorningMeetingTypes;