const types = {
    FETCH_SCRAP_VARIANCE_START: 'FETCH_SCRAP_VARIANCE_START',
    FETCH_SCRAP_VARIANCE_SUCCESS: 'FETCH_SCRAP_VARIANCE_SUCCESS',
    FETCH_SCRAP_VARIANCE_FAILURE: 'FETCH_SCRAP_VARIANCE_FAILURE',

    FETCH_PPMH_PER_DEPT_START: 'FETCH_PPMH_PER_DEPT_START',
    FETCH_PPMH_PER_DEPT_SUCCESS: 'FETCH_PPMH_PER_DEPT_SUCCESS',
    FETCH_PPMH_PER_DEPT_FAILURE: 'FETCH_PPMH_PER_DEPT_FAILURE',

    FETCH_PLANT_PPMH_START: 'FETCH_PLANT_PPMH_START',
    FETCH_PLANT_PPMH_SUCCESS: 'FETCH_PLANT_PPMH_SUCCESS',
    FETCH_PLANT_PPMH_FAILURE: 'FETCH_PLANT_PPMH_FAILURE',

    FETCH_SCRAP_VARIANCE_PER_PROGRAM_START: 'FETCH_SCRAP_VARIANCE_PER_PROGRAM_START',
    FETCH_SCRAP_VARIANCE_PER_PROGRAM_SUCCESS: 'FETCH_SCRAP_VARIANCE_PER_PROGRAM_SUCCESS',
    FETCH_SCRAP_VARIANCE_PER_PROGRAM_FAILURE: 'FETCH_SCRAP_VARIANCE_PER_PROGRAM_FAILURE',

    FETCH_DEPT_KPI_START: 'FETCH_DEPT_KPI_START',
    FETCH_DEPT_KPI_SUCCESS: 'FETCH_DEPT_KPI_SUCCESS',
    FETCH_DEPT_KPI_FAILURE: 'FETCH_DEPT_KPI_FAILURE',

    SET_DEPARTMENT: 'SET_DEPARTMENT',
}

export default types;