const productionDetailsTypes = {
    SET_PRODUCTION_DETAILS_TITLE: 'SET_PRODUCTION_DETAILS_TITLE',
    SET_PRODUCTION_DETAILS_AREA: 'SET_PRODUCTION_DETAILS_AREA',
    
    SET_PRODUCTION_DETAILS_START_DATE: 'SET_PRODUCTION_DETAILS_START_DATE',
    SET_PRODUCTION_DETAILS_END_DATE: 'SET_PRODUCTION_DETAILS_END_DATE',

    FETCH_PRODUCTION_DETAILS_START: 'FETCH_PRODUCTION_DETAILS_START',
    FETCH_PRODUCTION_DETAILS_SUCCESS: 'FETCH_PRODUCTION_DETAILS_SUCCESS',
    FETCH_PRODUCTION_DETAILS_FAILURE: 'FETCH_PRODUCTION_DETAILS_FAILURE'
}

export default productionDetailsTypes;