const productionStatusTypes = {
    SET_DEPARTMENT: 'SET_DEPARTMENT',
    SET_SHIFT: 'SET_SHIFT',
    SET_DATE_RANGE: 'SET_DATE_RANGE',

    SET_PRODUCTION_STATUS: 'SET_PRODUCTION_STATUS',
    SET_SCRAP_MODAL_VISIBLE: 'SET_SCRAP_MODAL_VISIBLE',
    SET_DOWNTIME_MODAL_VISIBLE: 'SET_DOWNTIME_MODAL_VISIBLE',
    SET_HXH_MODAL_VISIBLE: 'SET_HXH_MODAL_VISIBLE',

    SET_LINE: 'SET_LINE',
    SET_SCRAP_COLLECTION: 'SET_SCRAP_COLLECTION',
    SET_DOWNTIME_BY_MACHINE_COLLECTION: 'SET_DOWNTIME_BY_MACHINE_COLLECTION',
    SET_DOWNTIME_BY_REASON_COLLECTION: 'SET_DOWNTIME_BY_REASON_COLLECTION',
    SET_HXH_COLLECTION: 'SET_HXH_COLLECTION',
    SET_TARGET: 'SET_TARGET'
}

export default productionStatusTypes;