const SwotTypes = {
    FETCH_SWOT_START: 'FETCH_SWOT_START',
    FETCH_SWOT_SUCCESS: 'FETCH_SWOT_SUCCESS',
    FETCH_SWOT_FAILURE: 'FETCH_SWOT_FAILURE',
    SET_DEPT: 'SET_DEPT'
}

export default SwotTypes;