const qualityCheckSheetTypes = {
    FETCH_LINE_START: 'FETCH_LINE_START',
    FETCH_LINE_SUCCESS: 'FETCH_LINE_SUCCESS',
    FETCH_LINE_FAILURE: 'FETCH_LINE_FAILURE',

    FETCH_MACHINE_START: 'FETCH_MACHINE_START',
    FETCH_MACHINE_SUCCESS: 'FETCH_MACHINE_SUCCESS',
    FETCH_MACHINE_FAILURE: 'FETCH_MACHINE_FAILURE',

    FETCH_SUB_MACHINE_START: 'FETCH_SUB_MACHINE_START',
    FETCH_SUB_MACHINE_SUCCESS: 'FETCH_SUB_MACHINE_SUCCESS',
    FETCH_SUB_MACHINE_FAILURE: 'FETCH_SUB_MACHINE_FAILURE',

    FETCH_PART_START: 'FETCH_PART_START',
    FETCH_PART_SUCCESS: 'FETCH_PART_SUCCESS',
    FETCH_PART_FAILURE: 'FETCH_PART_FAILURE',

    FETCH_CHARACTERISTICS_START: 'FETCH_CHARACTERISTICS_START',
    FETCH_CHARACTERISTICS_SUCCESS: 'FETCH_CHARACTERISTICS_SUCCESS',
    FETCH_CHARACTERISTICS_FAILURE: 'FETCH_CHARACTERISTICS_FAILURE',

    SET_CONTROL_METHOD: 'SET_CONTROL_METHOD',
    SET_PART: 'SET_PART',
    SET_MACHINE: 'SET_MACHINE',

    SET_CHECK_SHEET_PART: 'SET_CHECK_SHEET_PART',
    SET_CHECK_SHEET_SUB_MACHINE: 'SET_CHECK_SHEET_SUB_MACHINE',
    SET_CHECK_SHEET_MACHINE_NAME: 'SET_CHECK_SHEET_MACHINE_NAME',

    SET_RE_CHECKS: 'SET_RE_CHECKS',
    SET_CHECK_SHEET_VALUES: 'SET_CHECK_SHEET_VALUES',
}

export default qualityCheckSheetTypes;