const qualityCheckSheetTypes = {
    FETCH_LINE_START: 'FETCH_LINE_START',
    FETCH_LINE_SUCCESS: 'FETCH_LINE_SUCCESS',
    FETCH_LINE_FAILURE: 'FETCH_LINE_FAILURE',

    FETCH_MACHINE_START: 'FETCH_MACHINE_START',
    FETCH_MACHINE_SUCCESS: 'FETCH_MACHINE_SUCCESS',
    FETCH_MACHINE_FAILURE: 'FETCH_MACHINE_FAILURE',

    FETCH_SUB_MACHINE_START: 'FETCH_SUB_MACHINE_START',
    FETCH_SUB_MACHINE_SUCCESS: 'FETCH_SUB_MACHINE_SUCCESS',
    FETCH_SUB_MACHINE_FAILURE: 'FETCH_SUB_MACHINE_FAILURE',

    FETCH_PART_START: 'FETCH_PART_START',
    FETCH_PART_SUCCESS: 'FETCH_PART_SUCCESS',
    FETCH_PART_FAILURE: 'FETCH_PART_FAILURE',

    FETCH_CHARACTERISTICS_START: 'FETCH_CHARACTERISTICS_START',
    FETCH_CHARACTERISTICS_SUCCESS: 'FETCH_CHARACTERISTICS_SUCCESS',
    FETCH_CHARACTERISTICS_FAILURE: 'FETCH_CHARACTERISTICS_FAILURE',

    SET_CONTROL_METHOD: 'SET_CONTROL_METHOD',
    SET_PART: 'SET_PART',
    SET_LINE: 'SET_LINE'
}

export default qualityCheckSheetTypes;