const OrderStatusTypes = {
    FETCH_WORKCENTER_START: 'FETCH_WORKCENTER_START',
    FETCH_WORKCENTER_SUCCESS: 'FETCH_WORKCENTER_SUCCESS',
    FETCH_WORKCENTER_FAILURE: 'FETCH_WORKCENTER_FAILURE'
}

export default OrderStatusTypes;