const AfEosTypes = {
    FETCH_DEPT_LINES_START: 'FETCH_DEPT_LINES_START',
    FETCH_DEPT_LINES_SUCCESS: 'FETCH_DEPT_LINES_SUCCESS',
    FETCH_DEPT_LINES_FAILURE: 'FETCH_DEPT_LINES_FAILURE',

    FETCH_DEPT_EOS_START: 'FETC_DEPT_EOS_START',
    FETCH_DEPT_EOS_SUCCESS: 'FETC_DEPT_EOS_SUCCESS',
    FETCH_DEPT_EOS_FAILURE: 'FETC_DEPT_EOS_FAILURE',

    SET_DEPT_EOS_RESULT: 'SET_DEPT_EOS_RESULT',

    SET_DEPT_EOS_COLLECTION: 'SET_DEPT_EOS_COLLECTION',

    FETCH_DEPT_EOS_COLLECTION_START: 'FETCH_DEPT_EOS_COLLECTION_START',
    FETCH_DEPT_EOS_COLLECTION_SUCCESS: 'FETCH_DEPT_EOS_COLLECTION_SUCCESS',
    FETCH_DEPT_EOS_COLLECTION_FAILURE: 'FETCH_DEPT_EOS_COLLECTION_FAILURE'
}

export default AfEosTypes;