const types = {
    FETCH_SCRAP_VARIANCE_BY_DEPT_START: 'FETCH_SCRAP_VARIANCE_BY_DEPT_START',
    FETCH_SCRAP_VARIANCE_BY_DEPT_SUCCESS: 'FETCH_SCRAP_VARIANCE_BY_DEPT_SUCCESS',
    FETCH_SCRAP_VARIANCE_BY_DEPT_FAILURE: 'FETCH_SCRAP_VARIANCE_BY_DEPT_FAILURE',

    FETCH_SCRAP_VARIANCE_BY_SHIFT_START: 'FETCH_SCRAP_VARIANCE_BY_SHIFT_START',
    FETCH_SCRAP_VARIANCE_BY_SHIFT_SUCCESS: 'FETCH_SCRAP_VARIANCE_BY_SHIFT_SUCCESS',
    FETCH_SCRAP_VARIANCE_BY_SHIFT_FAILURE: 'FETCH_SCRAP_VARIANCE_BY_SHIFT_FAILURE',

    FETCH_OVERTIME_QUARTER_START: 'FETCH_OVERTIME_QUARTER_START',
    FETCH_OVERTIME_QUARTER_SUCCESS: 'FETCH_OVERTIME_QUARTER_SUCCESS',
    FETCH_OVERTIME_QUARTER_FAILURE: 'FETCH_OVERTIME_QUARTER_FAILURE',

    FETCH_OVERTIME_SHIFT_START: 'FETCH_OVERTIME_SHIFT_START',
    FETCH_OVERTIME_SHIFT_SUCCESS: 'FETCH_OVERTIME_SHIFT_SUCCESS',
    FETCH_OVERTIME_SHIFT_FAILURE: 'FETCH_OVERTIME_SHIFT_FAILURE',
}

export default types;