const types = {
    FETCH_LOGISTICS_STOCK_OVERVIEW_START: 'FETCH_LOGISTICS_STOCK_OVERVIEW_START',
    FETCH_LOGISTICS_STOCK_OVERVIEW_SUCCESS: 'FETCH_LOGISTICS_STOCK_OVERVIEW_SUCCESS',
    FETCH_LOGISTICS_STOCK_OVERVIEW_FAILURE: 'FETCH_LOGISTICS_STOCK_OVERVIEW_FAILURE',

    FETCH_LOGISTICS_STOCK_OVERVIEW_SLOC_START: 'FETCH_LOGISTICS_STOCK_OVERVIEW_SLOC_START',
    FETCH_LOGISTICS_STOCK_OVERVIEW_SLOC_SUCCESS: 'FETCH_LOGISTICS_STOCK_OVERVIEW_SLOC_SUCCESS',
    FETCH_LOGISTICS_STOCK_OVERVIEW_SLOC_FAILURE: 'FETCH_LOGISTICS_STOCK_OVERVIEW_SLOC_FAILURE',

    FETCH_LOGISTICS_STATUS_START: 'FETCH_LOGISTICS_STATUS_START',
    FETCH_LOGISTICS_STATUS_SUCCESS: 'FETCH_LOGISTICS_STATUS_SUCCESS',
    FETCH_LOGISTICS_STATUS_FAILURE: 'FETCH_LOGISTICS_STATUS_FAILURE',
}

export default types;