const MorningMeetingTypes = {

    //* finance


    //* downtime
    FETCH_DOWNTIME_START: 'FETCH_DOWNTIME_START',
    FETCH_DOWNTIME_SUCCESS: 'FETCH_DOWNTIME_SUCCESS',
    FETCH_DOWNTIME_FAILURE: 'FETCH_DOWNTIME_FAILURE',

    FETCH_DOWNTIME_BY_OWNER_START: 'FETCH_DOWNTIME_BY_OWNER_START',
    FETCH_DOWNTIME_BY_OWNER_SUCCESS: 'FETCH_DOWNTIME_BY_OWNER_SUCCESS',
    FETCH_DOWNTIME_BY_OWNER_FAILURE: 'FETCH_DOWNTIME_BY_OWNER_FAILURE',

    FETCH_DOWNTIME_ICONICS_START: 'FETCH_DOWNTIME_ICONICS_START',
    FETCH_DOWNTIME_ICONICS_SUCCESS: 'FETCH_DOWNTIME_ICONICS_SUCCESS',
    FETCH_DOWNTIME_ICONICS_FAILURE: 'FETCH_DOWNTIME_ICONICS_FAILURE',

    //* performance
    FETCH_SCRAP_VARIANCE_START: 'FETCH_SCRAP_VARIANCE_START',
    FETCH_SCRAP_VARIANCE_SUCCESS: 'FETCH_SCRAP_VARIANCE_SUCCESS',
    FETCH_SCRAP_VARIANCE_FAILURE: 'FETCH_SCRAP_VARIANCE_FAILURE',

    FETCH_SCRAP_VARIANCE_PER_PROGRAM_START: 'FETCH_SCRAP_VARIANCE_PER_PROGRAM_START',
    FETCH_SCRAP_VARIANCE_PER_PROGRAM_SUCCESS: 'FETCH_SCRAP_VARIANCE_PER_PROGRAM_SUCCESS',
    FETCH_SCRAP_VARIANCE_PER_PROGRAM_FAILURE: 'FETCH_SCRAP_VARIANCE_PER_PROGRAM_FAILURE',

    FETCH_DEPT_KPI_START: 'FETCH_DEPT_KPI_START',
    FETCH_DEPT_KPI_SUCCESS: 'FETCH_DEPT_KPI_SUCCESS',
    FETCH_DEPT_KPI_FAILURE: 'FETCH_DEPT_KPI_FAILURE',

    FETCH_SCRAP_VARIANCE_BY_DEPT_START: 'FETCH_SCRAP_VARIANCE_BY_DEPT_START',
    FETCH_SCRAP_VARIANCE_BY_DEPT_SUCCESS: 'FETCH_SCRAP_VARIANCE_BY_DEPT_SUCCESS',
    FETCH_SCRAP_VARIANCE_BY_DEPT_FAILURE: 'FETCH_SCRAP_VARIANCE_BY_DEPT_FAILURE',

    FETCH_SCRAP_VARIANCE_BY_SHIFT_START: 'FETCH_SCRAP_VARIANCE_BY_SHIFT_START',
    FETCH_SCRAP_VARIANCE_BY_SHIFT_SUCCESS: 'FETCH_SCRAP_VARIANCE_BY_SHIFT_SUCCESS',
    FETCH_SCRAP_VARIANCE_BY_SHIFT_FAILURE: 'FETCH_SCRAP_VARIANCE_BY_SHIFT_FAILURE',

    FETCH_PPMH_PER_DEPT_START: 'FETCH_PPMH_PER_DEPT_START',
    FETCH_PPMH_PER_DEPT_SUCCESS: 'FETCH_PPMH_PER_DEPT_SUCCESS',
    FETCH_PPMH_PER_DEPT_FAILURE: 'FETCH_PPMH_PER_DEPT_FAILURE',

    FETCH_PLANT_PPMH_START: 'FETCH_PLANT_PPMH_START',
    FETCH_PLANT_PPMH_SUCCESS: 'FETCH_PLANT_PPMH_SUCCESS',
    FETCH_PLANT_PPMH_FAILURE: 'FETCH_PLANT_PPMH_FAILURE',

    FETCH_OVERTIME_PERCENT_PER_DEPT_START: 'FETCH_OVERTIME_PERCENT_PER_DEPT_START',
    FETCH_OVERTIME_PERCENT_PER_DEPT_SUCCESS: 'FETCH_OVERTIME_PERCENT_PER_DEPT_SUCCESS',
    FETCH_OVERTIME_PERCENT_PER_DEPT_FAILURE: 'FETCH_OVERTIME_PERCENT_PER_DEPT_FAILURE',

    FETCH_OVERTIME_PERCENT_PER_SHIFT_START: 'FETCH_OVERTIME_PERCENT_PER_SHIFT_START',
    FETCH_OVERTIME_PERCENT_PER_SHIFT_SUCCESS: 'FETCH_OVERTIME_PERCENT_PER_SHIFT_SUCCESS',
    FETCH_OVERTIME_PERCENT_PER_SHIFT_FAILURE: 'FETCH_OVERTIME_PERCENT_PER_SHIFT_FAILURE',

    SET_PRODUCTION_START_DATE: 'SET_PRODUCTION_START_DATE',
    SET_PRODUCTION_END_DATE: 'SET_PRODUCTION_END_DATE',

    SET_DOWNTIME_BY_OWNER: 'SET_DOWNTIME_BY_OWNER',
    SET_DOWNTIME_BY_LINE: 'SET_DOWNTIME_BY_LINE',

    SET_DEPARTMENT_SELECT: 'SET_DEPARTMENT_SELECT',
    SET_PPMH_CHART_TYPE: 'SET_PPMH_CHART_TYPE',

    FETCH_HOURLY_PROD_START: 'FETCH_HOURLY_PROD_START',
    FETCH_HOURLY_PROD_SUCCESS: 'FETCH_HOURLY_PROD_SUCCESS',
    FETCH_HOURLY_PROD_FAILURE: 'FETCH_HOURLY_PROD_FAILURE',
}

export default MorningMeetingTypes;