const types = {

    FETCH_LINE_START: 'FETCH_LINE_START',
    FETCH_LINE_SUCCESS: 'FETCH_LINE_SUCCESS',
    FETCH_LINE_FAILURE: 'FETCH_LINE_FAILURE',

    FETCH_OEE_START: 'FETCH_OEE_START',
    FETCH_OEE_SUCCESS: 'FETCH_OEE_SUCCESS',
    FETCH_OEE_FAILURE: 'FETCH_OEE_FAILURE',

    FETCH_MACHINES_START: 'FETCH_MACHINES_START',
    FETCH_MACHINES_SUCCESS: 'FETCH_MACHINES_SUCCESS',
    FETCH_MACHINES_FAILURE: 'FETCH_MACHINES_FAILURE',

    FETCH_REASON1_START: 'FETCH_REASON1_START',
    FETCH_REASON1_SUCCESS: 'FETCH_REASON1_SUCCESS',
    FETCH_REASON1_FAILURE: 'FETCH_REASON1_FAILURE',

    FETCH_REASON2_START: 'FETCH_REASON2_START',
    FETCH_REASON2_SUCCESS: 'FETCH_REASON2_SUCCESS',
    FETCH_REASON2_FAILURE: 'FETCH_REASON2_FAILURE',

    SET_RECORD: 'SET_RECORD',
    SET_SUB_TITLE: 'SET_SUB_TITLE'
}

export default types;