const types = {
    FETCH_DOWNTIME_START: 'FETCH_DOWNTIME_START',
    FETCH_DOWNTIME_SUCCESS: 'FETCH_DOWNTIME_SUCCESS',
    FETCH_DOWNTIME_FAILURE: 'FETCH_DOWNTIME_FAILURE',

    FETCH_DOWNTIME_BY_OWNER_START: 'FETCH_DOWNTIME_BY_OWNER_START',
    FETCH_DOWNTIME_BY_OWNER_SUCCESS: 'FETCH_DOWNTIME_BY_OWNER_SUCCESS',
    FETCH_DOWNTIME_BY_OWNER_FAILURE: 'FETCH_DOWNTIME_BY_OWNER_FAILURE',

    FETCH_DOWNTIME_ICONICS_START: 'FETCH_DOWNTIME_ICONICS_START',
    FETCH_DOWNTIME_ICONICS_SUCCESS: 'FETCH_DOWNTIME_ICONICS_SUCCESS',
    FETCH_DOWNTIME_ICONICS_FAILURE: 'FETCH_DOWNTIME_ICONICS_FAILURE',

    SET_DOWNTIME_BY_OWNER: 'SET_DOWNTIME_BY_OWNER',
    SET_DOWNTIME_BY_LINE: 'SET_DOWNTIME_BY_LINE',
}

export default types;