const SwotTypes = {
    FETCH_SWOT_START: 'FETCH_SWOT_START',
    FETCH_SWOT_SUCCESS: 'FETCH_SWOT_SUCCESS',
    FETCH_SWOT_FAILURE: 'FETCH_SWOT_FAILURE',
    SET_DEPT: 'SET_DEPT',
    SET_CHART_WIDTH: 'SET_CHART_WIDTH',
    SET_CHART_HEIGHT: 'SET_CHART_HEIGHT',
    SET_CHART_PRINT_WIDTH: 'SET_CHART_PRINT_WIDTH',
    SET_CHART_PRINT_HEIGHT: 'SET_CHART_PRINT_HEIGHT'
}

export default SwotTypes;